gamenet: Add 0.7 server info fields
heinrich5991/libtw2 pull request #100
Opened 2024-06-23 01:50 UTC by ChillerDragon

Generated using

```bash
cd gamenet/generate
python3 serialize.py --version 0.7 raw/teeworlds-0.7.5.py > spec/teeworlds-0.7.5.json
cd ../../
./generate_all
```

Tested using the wireshark dissector

![image](https://github.com/heinrich5991/libtw2/assets/20344300/ecbcbc2f-bb34-4bf3-9634-e8276f03993e)

2024-06-24 13:11 UTC, heinrich5991 requested changes
Thanks for the PR. It looks good to me. In order to match the existing serverinfo fields in `gamenet`, could you rename them as I suggested?

2024-06-24 13:11 UTC, heinrich5991 commented on gamenet/generate/msg_system.py
> +    ( 4, "server_info", "vital", "s:version s:name s:hostname s:map_name s:game_type i:flags i:skill_level i:player_count i:player_slots i:client_count i:max_clients"),
```suggestion
    ( 4, "server_info", "vital", "s:version s:name s:hostname s:map s:game_type i:flags i:skill_level i:num_players i:max_players i:num_clients i:max_clients"),
```

2024-06-25 12:29 UTC, heinrich5991 approved these changes
I generated the data again (seems to have been forgotten) and squashed the commits. Does it also look good to you now, @ChillerDragon?

2024-06-25 13:00 UTC, ChillerDragon commented
didn't test but LGTM

Yeah I just clicked the GitHub button to commit your changes 🙈 thats why the generate was missing.

2024-06-25 13:04 UTC, merged